[package]
name = "boiler_core"
version = "0.1.0"
description = "TODO"
authors = ["Mateusz MaÄ‡kowski <mateusz@mackowski.org>"]
readme = "../README.md"
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.79"
boiler_macros = { path = "../boiler_macros" }
chrono = "0.4.31"
comrak = "0.21.0"
gix = { version = "0.58.0", features = ["basic"] }
ignore = "0.4.22"
log = "0.4.20"
once_cell = "1.19.0"
regex = "1.10.2"
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.30"
tera = "1.19.1"
thiserror = "1.0.56"
toml = "0.8.8"
